name: Build Electron App

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build main and renderer (treeshaking)
        run: |
          npx esbuild main.js --bundle --platform=node --minify --outfile=dist/main.js --log-level=error


      - name: Build Windows (32 + 64 bit)
        if: matrix.os == 'windows-latest'
        run: npx electron-builder --win --ia32 --x64 --publish=never

      - name: Build Windows (32 + 64 bit)        
        if: matrix.os == 'ubuntu-latest'
        run: npm run dist -- --publish=never

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: stacker-${{ matrix.os }}
          path: dist/*.exe
