name: Deploy Website to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write  # Crucial: allows pushing to the gh-pages branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Ensure Lockfile exists 🛠️
        run: |
          if [ ! -f package-lock.json ]; then
            npm i --package-lock-only
          fi
        working-directory: website

      - name: Setup Node.js ⚙️
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: website/package-lock.json

      - name: Install dependencies 🔧
        run: npm install
        working-directory: website

      - name: Build project 🏗️
        run: npm run build:ghpages
        working-directory: website

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: website/dist  # Where Webpack put the files
          branch: gh-pages      # The branch it will push to
          clean: true           # Automatically remove old files from gh-pages
